version: '3'
services:
  client1:
    container_name: edge-device_client01
    image: fdo-client-test-304231616:latest
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./client01-manufacturer_sn.bin:/opt/fdo/data/manufacturer_sn.bin
  client2:
    container_name: edge-device_client02
    image: fdo-client-test-304231616:latest
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./client02-manufacturer_sn.bin:/opt/fdo/data/manufacturer_sn.bin
  client3:
    container_name: edge-device_client03
    image: fdo-client-test-304231616:latest
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./client03-manufacturer_sn.bin:/opt/fdo/data/manufacturer_sn.bin
  client4:
    container_name: edge-device_client04
    image: fdo-client-test-304231616:latest
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./client04-manufacturer_sn.bin:/opt/fdo/data/manufacturer_sn.bin
  client5:
    container_name: edge-device_client05
    image: fdo-client-test-304231616:latest
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./client05-manufacturer_sn.bin:/opt/fdo/data/manufacturer_sn.bin
  client6:
    container_name: edge-device_client06
    image: fdo-client-test-304231616:latest
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./client06-manufacturer_sn.bin:/opt/fdo/data/manufacturer_sn.bin
  client7:
    container_name: edge-device_client07
    image: fdo-client-test-304231616:latest
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./client07-manufacturer_sn.bin:/opt/fdo/data/manufacturer_sn.bin
  client8:
    container_name: edge-device_client08
    image: fdo-client-test-304231616:latest
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./client08-manufacturer_sn.bin:/opt/fdo/data/manufacturer_sn.bin
  client9:
    container_name: edge-device_client09
    image: fdo-client-test-304231616:latest
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./client09-manufacturer_sn.bin:/opt/fdo/data/manufacturer_sn.bin
  client10:
    container_name: edge-device_client10
    image: fdo-client-test-304231616:latest
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./client10-manufacturer_sn.bin:/opt/fdo/data/manufacturer_sn.bin
